language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed chidigodwin/udagram-api-feed:v1
  - docker tag udagram-api-user chidigodwin/udagram-api-user:v1
  - docker tag reverseproxy chidigodwin/reverseproxy:v1
  - docker tag udagram-frontend chidigodwin/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chidigodwin/udagram-api-feed:v1
  - docker push chidigodwin/udagram-api-user:v1
  - docker push chidigodwin/reverseproxy:v1
  - docker push chidigodwin/udagram-frontend:v1